#!/usr/bin/env node

const os = require('os');
const { spawn } = require('child_process');
const path = require('path');

let command = 'docs-cli.js';
if (os.platform() === 'win32') {
  command = 'docs-cli-win.exe';
}

const cliPath = path.join(__dirname, 'cli', 'dist', command);
const args = process.argv.slice(2);

const child = spawn('node', [cliPath, ...args], { stdio: 'inherit' });

child.on('exit', (code) => {
  process.exit(code);
});